cask_args appdir: "/Applications"

# Tap Homebrew
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# Apps
cask "iterm2"
cask "visual-studio-code"
cask "postman"
cask "firefox"
cask "font-hack-nerd-font"
cask "font-fira-code"
cask "docker"

# System
brew "coreutils"
brew "curl"
brew "wget"
brew "git"
brew "gh"
brew "tree"
brew "entr"
brew "pidof"
brew "pstree"
brew "grep"
brew "openssl"
brew "openssh"
brew "exa"
brew "bat"
brew "jq"
brew "jo"
brew "gron"
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "fzf"
brew "awscli"
brew "spaceship"
